# Generated by Django 4.1 on 2023-05-25 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_date_created_profile_name_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='his_item', to='home.item')),
                ('user_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hist_client', to='home.profile')),
                ('user_vendodor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hist_vendedor', to='home.profile')),
            ],
        ),
    ]
