# Generated by Django 4.1 on 2023-05-25 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='data_compra',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
