# Generated by Django 4.1 on 2023-05-29 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_historico_data_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificações',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complite_compra', models.FloatField(default=0)),
                ('cancel_compra', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_notificacoes', to='home.profile')),
            ],
        ),
    ]
