# Generated by Django 4.1 on 2023-05-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_notificações'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificações',
        ),
    ]
