# Generated by Django 4.2 on 2023-04-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('descricao', models.TextField(blank=True, default='Ecreva sua descrição', max_length=150)),
                ('produto_imagem', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
