# Generated by Django 4.1 on 2023-04-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('PROMOÇÃO', 'Promoção'), ('PARA VOCÊ', 'Para você')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='produto_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
