# Generated by Django 4.1 on 2023-04-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_category_item_category_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
