# Generated by Django 4.1 on 2023-05-08 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itens_carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_car', to='home.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_car', to='home.profile')),
            ],
        ),
    ]
