# Generated by Django 4.2.1 on 2023-05-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_customer_profile_pic_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='0000-0000', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
